# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: >-
  (?x)^(
    .*\.diff
  )$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-merge-conflict
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/jjmaestro/pre-commit-buildifier
  rev: fix-support-MODULE-includes
  hooks:
    - id: buildifier
      args: &args
        - --warnings=all
    - id: buildifier-lint
      args: *args
